        
resources:
- name: concourse-aws
  type: git
  source:
    uri: https://github.com/saikrishna-tlsr/Terraform.git
    branch: master
    
- name: terraform
  type: docker-image
  check_every: 1m
  source:
    repository: ((docker-repo))/((docker-terraform))
    tag: ((docker-tag))
    
- name: vpc
  type: git
  source:
    uri: https://github.com/saikrishna-tlsr/Terraform.git/vpc.tf
    branch: master
    

jobs:
- name: vpc creation
  plan:
  - aggregate:
    - get: concourse-aws
    - get: terraform
  - task: aws infrastructure
    file: concourse-aws/pipeline.yml
    
 
